name: CustomizeFishing
version: '1.0-SNAPSHOT'
main: io.wax100.customizeFishing.CustomizeFishing
api-version: '1.20'
author: wax100
description: Customize fishing loot tables with advanced conditions

commands:
  customizefishing:
    description: Main command for CustomizeFishing plugin
    usage: /<command> [reload|debugrod|help]
    aliases: [cf, cfish]
    permission: customizefishing.use

permissions:
  customizefishing.use:
    description: Allows use of basic CustomizeFishing commands
    default: true
  customizefishing.reload:
    description: Allows reloading the plugin configuration
    default: op
  customizefishing.debugrod:
    description: Allows creating debug fishing rods
    default: op
  customizefishing.*:
    description: Gives access to all CustomizeFishing permissions
    default: op
    children:
      customizefishing.use: true
      customizefishing.reload: true
      customizefishing.debugrod: true
